import type { RunReport, BehaviorSummary } from '../types/spec.js';

function statusBadge(passed: boolean): string {
  return passed ? '✅ Pass' : '❌ Fail';
}

function scoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return '█'.repeat(filled) + '░'.repeat(10 - filled);
}

function behaviorRow(b: BehaviorSummary): string {
  const badge = statusBadge(b.passed);
  const bar = scoreBar(b.passRate);
  const topFailure = b.results.find((r) => !r.passed);
  const failNote = topFailure?.failureReason
    ? `<br><sub>⚠ ${topFailure.failureReason.slice(0, 120)}</sub>`
    : '';

  return `| ${badge} | ${b.name} | \`${bar}\` ${b.passRate.toFixed(1)}% | ${b.passedTests}/${b.totalTests} |${failNote} |`;
}

/** Generate a GitHub PR comment in Markdown */
export function buildGithubComment(report: RunReport): string {
  const header = report.passed
    ? '## ✅ BehaviorCI — All behaviors passed'
    : '## ❌ BehaviorCI — Behavioral regression detected';

  const meta = [
    `**Feature:** ${report.specName}`,
    `**Score:** ${report.overallScore.toFixed(1)}% (threshold: ${report.threshold}%)`,
    `**Tests:** ${report.passedTests}/${report.totalTests} passed`,
    `**Duration:** ${(report.durationMs / 1000).toFixed(1)}s`,
    report.commitSha ? `**Commit:** \`${report.commitSha.slice(0, 8)}\`` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  const tableHeader = `| Status | Behavior | Score | Tests |
|--------|----------|-------|-------|`;

  const rows = report.behaviors.map(behaviorRow).join('\n');

  const failedBehaviors = report.behaviors.filter((b) => !b.passed);
  const failureDetail =
    failedBehaviors.length > 0
      ? `\n### Failed Behaviors\n${failedBehaviors
          .map((b) => {
            const failures = b.results.filter((r) => !r.passed).slice(0, 2);
            return (
              `**${b.name}** — ${b.passRate.toFixed(1)}% pass rate\n` +
              failures
                .map(
                  (f) =>
                    `> **Input:** ${f.input.slice(0, 100)}\n> **Output:** ${(f.actualOutput || '*(empty)*').slice(0, 100)}\n> **Reason:** ${f.failureReason ?? 'N/A'}`
                )
                .join('\n\n')
            );
          })
          .join('\n\n')}`
      : '';

  const footer = `<sub>Generated by [BehaviorCI](https://github.com/behaviourci/behaviourci) · ${new Date(report.startedAt).toUTCString()}</sub>`;

  return [header, meta, tableHeader, rows, failureDetail, footer].filter(Boolean).join('\n\n');
}
